const ASSISTANT_CONTRACT_BUNDLE_VERSION = "assistant-contract-bundle-v1";
const ASSISTANT_READINESS_VERSION = "assistant-readiness-v1";
const ASSISTANT_STUDY_PLAN_DRY_RUN_VERSION = "assistant-study-plan-dry-run-v1";
const ASSISTANT_STUDY_PLAN_LIVE_DRAFT_VERSION = "assistant-study-plan-live-draft-v1";

export {
  ASSISTANT_CONTRACT_BUNDLE_VERSION,
  ASSISTANT_READINESS_VERSION,
  ASSISTANT_STUDY_PLAN_DRY_RUN_VERSION,
  ASSISTANT_STUDY_PLAN_LIVE_DRAFT_VERSION,
};
